# Theme settings
doks:
    baseurl:
    color_theme: green # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Computing Documentation
            image: 
        nav:
        
    footer:
        content:
            logo:
                image: true
            copyright: Copyright Matt Watkins &copy; 2021. <br>All rights reserved.

    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
plugins: - jekyll-katex
